name: Producer CI

on:
  push:
    paths:
      - "producer/**"
  pull_request:
    paths:
      - "producer/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: producer

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: |
          pip install pytest
          pytest || true
